version: "3.9"

services:
  nginx: 
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    restart: always

  flask_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 app:app
    volumes:
      - ./:/var/www
    networks:
      - my-network
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    links:
      - flask_db
    restart: always


  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres 
      - POSTGRES_PORT=5432
    networks:
      - my-network

networks:
  my-network:
