version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
        # networks:
      # - monitoring
    

  nginx: 
    image: nginx:1.15
      # container_name: nginx
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    ports:
      #- "80:80"
      - "80:80"
      - "443:443" 
    restart: always
    depends_on:
      - flask_app
        # networks:
      # - monitoring
  


  flask_app:
    build: 
      dockerfile: Dockerfile 
        #container_name: flask_app
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 app:app
    # volumes:
    #   - ./:/var/www
    expose:
      - "5000"
        #ports:
        #- "80:80"
    deploy:
      replicas: 3
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    links:
      - flask_db
    restart: always
      # networks:
      #- monitoring

  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
        # networks:
        # - monitoring

  grafana:
    image: grafana/grafana:9.0.0
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
        # networks:
        # - monitoring
    


  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5430:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres 
      - POSTGRES_PORT=5432 
        # networks:
      # - monitoring

        # networks:
    #monitoring:
      #driver: bridge    
 
