version: "3.9"

services:
  nginx:
    depends_on:
      - flask_app
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
  flask_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.app:app()"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - flask-app
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

networks:
  my-network:
