version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  nginx: 
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80 
    restart: always

  flask_app:
    build: 
      dockerfile: Dockerfile 
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 app:app
    # volumes:
    #   - ./:/var/www 
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    links:
      - flask_db
    restart: always


  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5430:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres 
      - POSTGRES_PORT=5432 
 
